root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    quickstart/faculty-guides/education: ./README.md
    quickstart/getting-started-with-nuvolos: ./README.md
